### ISSUE TITLE
Link opening issue

### ISSUE THREAD

**Issue by Thunderbottom** [mthli/Ninja#11]
When you open link from google play store, it has a redirect url instead of direct link to website. So the browser performs a google search instead of opening the website. You can try it on Android 5.0 and above.

**Comment by mthli** [comment]
@balzathor See [this line](https://github.com/mthli/Ninja/blob/master/Ninja/src/io/github/mthli/Ninja/Unit/BrowserUnit.java#L96) and below, fix your issue.

You can do something just like what I do to solve lots of link error(to search).

**Comment by alexisju** [comment]
Same issue when you open a link from Google News app.
