### ISSUE TITLE
Add user option 

### ISSUE THREAD

**Issue by Thunderbottom** [mthli/Ninja#15]
can you add user option for image quality? 
Like user can select if the webpage loads images in low, medium or high quality?

**Comment by mthli** [comment]
No, I don't kown how to do this.

But here has 2 methods you can try:
1. Use JavaScript Inject to WebView.
2. Change UA.

There has no method to directly change image quality, so you have to do by
yourself.

Matthew Lee
2015年6月22日 04:27于 "Chinmay Pai" notifications@github.com写道：
