### ISSUE TITLE
Add Chrome sync

### ISSUE THREAD

**Issue by mthlifan** [mthli/Ninja#16]
I wanting Chrome Bookmark sync plss.
this browser will be best if added.

Thanks

**Comment by mthli** [comment]
Currently you can import Chrome html bookmark file to Ninja.

**Comment by mthlifan** [comment]
Yes, but need chrome sync so i take my bookmarks every where i go.
Pls do. Pls.

**Comment by mthli** [comment]
OK, let me thinking..

**Comment by mthlifan** [comment]
Plsss, I be your favor!!

**Comment by mthlifan** [comment]
Can add a option to open play store links in play store? twitter links in twitter? facebook links in facebook apps and other thing? Please do it. Now, it opens play store links in a webpage, but I want open it in play store. HELP PLS!!

**Comment by mthli** [comment]
OK I will try but currently mainly fix bugs.

**Comment by mthlifan** [comment]
where you? I not see update many days, give good update fast pls

**Comment by mthlifan** [comment]
take time but give good update with new feature, make nice

**Comment by mthli** [comment]
Sorry I feel tired and I have to prepare the final exam, so pause upgrade.

**Comment by mthlifan** [comment]
password not save? I try but it not save. Pls fix.
And how I open links in front? I dont want open in background, pls add too
