### ISSUE TITLE
How do I get current webpage as HTML?

### ISSUE THREAD

**Issue by Thunderbottom** [mthli/Ninja#17]
How do I save the current webpage as html?

**Comment by mthli** [comment]
Sorry, you have inject JS to WebView by yourself or, download html file
again.

Matthew Lee
2015年6月23日 23:52于 "Chinmay Pai" notifications@github.com写道：

**Comment by Thunderbottom** [comment]
Okay thanks and how do I know if the page is currently home page? in BrowserActivity?

**Comment by mthli** [comment]
See BrowserUnit, flag home tag, mm, just follow the flag you can get
homepage sourse code.

Matthew Lee
2015年6月23日 23:56于 "Chinmay Pai" notifications@github.com写道：

**Comment by Thunderbottom** [comment]
Thanks :)
