### ISSUE TITLE
I can help you add ACRA (Application Crash Report for Android) to Ninja

### ISSUE THREAD

**Issue by Thunderbottom** [mthli/Ninja#3]
If you want, I can help you add ACRA, which will send you log report when the application crashes, all I need is your Skype or something so we can talk and I can send you the code.

**Comment by Thunderbottom** [comment]
Details on ACRA can be found [here](http://www.acra.ch)

**Comment by mthli** [comment]
mmm, actually I don't like add ACRA for my browser now.

I create Ninja for fun and I hope to **design** it by my own, so some of features I may not want to add.

But I would like to add you to one of Ninja's contributors, and you can continue to build your own UBP :)

**Comment by Thunderbottom** [comment]
Thanks a lot, When I changed the strings, I forgot to add your name in the list, and since then I've never updated the string_app else for the version number. Added your name in it :)

Thanks :)
