### ISSUE TITLE
I have some browser issues (Download Crash issues)

### ISSUE THREAD

**Issue by Thunderbottom** [mthli/Ninja#6]
I took a look into @mthlifan 's issue about download error.
When any download starts in the background, the application crashes. Sometimes while downloading a file too, it happens
I do not understand where the problem is.
Here is the log file for the exact problem - 

```
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
 tat android.view.ViewRootImpl.setView(ViewRootImpl.java:566)
 tat android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:282)
 tat android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
 tat android.app.Dialog.show(Dialog.java:298)
 tat io.github.mthli.ninja.Browser.NinjaDownloadListener.onDownloadStart(NinjaDownloadListener.java:35)
 tat com.android.webview.chromium.WebViewContentsClientAdapter.onDownloadStart(WebViewContentsClientAdapter.java:876)
 tat com.android.org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:112)
 tat android.os.Handler.dispatchMessage(Handler.java:102)
 tat android.os.Looper.loop(Looper.java:135)
 tat android.app.ActivityThread.main(ActivityThread.java:5347)
 tat java.lang.reflect.Method.invoke(Native Method)
 tat java.lang.reflect.Method.invoke(Method.java:372)
 tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
 tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by Thunderbottom** [comment]
Please fix this issue asap.

Thanks :)

**Comment by mthli** [comment]
I will see it tomorrow, now I have to go to sleep, have a good night😴

Matthew Lee
2015年6月17日 00:42于 "Chinmay Pai" notifications@github.com写道：

**Comment by Thunderbottom** [comment]
@mthli has this issue been fixed in this update?

**Comment by mthli** [comment]
No, I just update Ninja in my plan, but I will try to fix it.

**Comment by Thunderbottom** [comment]
There is some problem with the mime type, when the download starts in any background tab, the application crashes. This makes the application unusable. Please help. I cannot understand much of your code due to the fact that you haven't added comments everywhere. 

Regards.

**Comment by mthli** [comment]
Well, see [this line](https://github.com/mthli/Ninja/blob/master/Ninja/src/io/github/mthli/Ninja/View/NinjaWebView.java#L74).

When `NinjaWebView` created by `Activity`, it works fine. But when load in background, `NinjaWebView` created by `Service`, so crash.

**Comment by Thunderbottom** [comment]
So it can't be fixed?

**Comment by mthli** [comment]
Maybe you can start a "dialog activity" to replace `AlertDialog`.

**Comment by Thunderbottom** [comment]
Can you not fix it? I cannot fix your code because there are no comments to understand what to fix. I can only add new stuff.

**Comment by mthli** [comment]
I would like to fix it, but it need time :)

**Comment by Thunderbottom** [comment]
Yeah, take your time. I have many new features to add. I also just added the custom agent on request by a person on XDA [here](http://forum.xda-developers.com/showpost.php?p=61249547&postcount=12) and I am just waiting for the download to be fixed so I can file an Over The Air (OTA) update through the application intent.

Regards.

**Comment by mthli** [comment]
Currently there is a simply way to fix it. Just remove the `AlertDialog` before download.

**Comment by Thunderbottom** [comment]
Where do I remove it from, and wouldn't it make the browser unstable?

**Comment by Thunderbottom** [comment]
Also when the pages are loading, the scroll bar is shown, is there a way to not show them while the page is loading? I know you can turn it off in the settings but isn't there other way to code it to not show when the page is loading? Here is a screenshot with the horizontal scroll bar -
![Bug](https://cloud.githubusercontent.com/assets/11243138/8203851/525a3a3e-1502-11e5-8eb0-249b64152914.png)

**Comment by mthli** [comment]
You can hide scrollbar before `WebView` load finish, show scrollbar when it load finish.

**Comment by Thunderbottom** [comment]
can you give me the code for that?

**Comment by mthli** [comment]
I haven't written it.

**Comment by Thunderbottom** [comment]
Oh, how big will it be? you know that I can't edit your code. You can take your time to write it.

Thanks.

**Comment by mthli** [comment]
Not much I think, but I also need to fix other bugs. Next version should be fine.

**Comment by Thunderbottom** [comment]
Alright, I'll wait and find out other things to add into the browser.
Also, Incognito mode [can be used as an activity](https://github.com/EginKaman/Browser-Owl-s/blob/master/src/acr/browser/thunder/IncognitoActivity.java) where cookies and history is false

**Comment by mthli** [comment]
Actually I don't like incognito mode.

**Comment by Thunderbottom** [comment]
Me too haha, but People need it. You know, private stuff. 
I might add it later sometime when I've learnt more about it.
Anyways, now you know why I can't update your code, I'm still learning.
