### ISSUE TITLE
Remove whitespaces and new lines from within string.xml

### ISSUE THREAD

**Issue by ghost** [mthli/Ninja#7]
I am not sure how Android handles this, but basically the following two examples are not identical:

```
    <string name="app_version">
        1.3.2
    </string>
```

```
    <string name="app_version">1.3.2</string>
```

The first one includes whitespaces and new lines.

**Comment by Thunderbottom** [comment]
No, the whitespace won't show up until you add this - `\u0020` or `&#160;`
New line is added only when - `\n` is used.
There's basically no difference between the first and the second example that you've shown

**Comment by ghost** [comment]
Oh, okay, this might be an issue of fdroidserver then.

Ref: https://gitlab.com/fdroid/fdroidserver/issues/97

**Comment by Thunderbottom** [comment]
Wait, can you present a screenshot displaying the bug?

**Comment by mthli** [comment]
@balzathor Yes.

**Comment by Thunderbottom** [comment]
Please show it here, I'll tell you what the problem is

**Comment by Thunderbottom** [comment]
Because I've tried it on like 100's of devices and no one has ever complained about that bug. Maybe F-Droid has some compilation problems, You know, like they might support Auto-Whitespacing by default.

**Comment by ghost** [comment]
I haven't looked at the resulting apk file, it's fdroids updatecheck that is causing issues. I will ping you when we fixed this.

**Comment by mthli** [comment]
@krt16s Thank you :)

**Comment by Thunderbottom** [comment]
@krt16s 
The [String Template](https://github.com/antlr/stringtemplate4) that you use needs to be checked.
