### ISSUE TITLE
Double-tap to exit requires several taps to actually exit

### ISSUE THREAD

**Issue by gusmd** [mthli/Ninja#9]
More of a UX issue then a bug, but here it goes.

When tapping the back button, the Toast notification shows with string `toast_double_taps_quit` ("Press again to exit", in EN). This uses the `NinjaToast` class, which has its delay set to 2000 ms. However, the `Timer` you are using to expire the double-taps in method `doubleTapsQuit()` is using `DOUBLE_TAPS_QUIT_DEFAULT` as its delay, which is set to 512 ms. Therefore, when the user press the back button multiple times but with intervals longer then 512 ms, the Toast keeps showing but the app never exits. 

A simple fix would be to set `DOUBLE_TAPS_QUIT_DEFAULT` to 2000 ms, the same duration of the Toast, so that the user expectations are met (that is, while "Press again to exit" is showing, he can press again and the app will exit).

**Comment by mthli** [comment]
OK, I will consider it :)

**Comment by mthli** [comment]
@gusmd See [this line](https://github.com/mthli/Ninja/blob/master/Ninja/src/io/github/mthli/Ninja/Activity/BrowserActivity.java#L56), set `DOUBLE_TAPS_QUIT_DEFAULT` to 2000 ms now :)
